### ISSUE TITLE
依赖项可能存在的问题 MoeFilter

### ISSUE THREAD

**Issue by Shizoukia** [CatMoe/AkaneLimbo#1]
在2023/06/13 8:00AM左右 SakuraStarOcean出现了无法连接服务器的情况，经过排查发现是因为AkaneLimbo和JPremium的配置问题导致的
在JPremium中配置的MainLimbo和LoginLimbo服务器无法识别并传送 AkaneLimbo可能存在未正常创建虚拟服务器的奇葩问题

可能导致的原因：MoeFilter的更新版本问题
目前最后一次commit的pom中指定的mf版本为api2 而最新版是api6 可能存在一定的兼容性问题 稍后将尝试更新依赖项更新一次 若可用我将推送一个更新依赖项的pom.xml上来

仅用作可能存在的问题报告检查
这次先不用麻烦Akkariin了我先逝逝

QwQ

**Comment by Shizoukia** [comment]
ok im sand of bi*ch
我是傻逼 我突然想起来limbo好像有个载体 今儿早上我上线的时候killadministrator会话时候不小心把你账户kill掉了然后好像炸了点啥
抱歉 打扰了 我是傻逼 ;w;

**Comment by FallenCrystal** [comment]
有的时候 话说好听一点还是好的w=

> ~~我不管我就要改你的评论 不准骂自己 我说的w!~~

> Reply: 可能导致的原因：MoeFilter的更新版本问题
因为新版本导致的问题基本不会发生在MoeFilter身上. 我尽量对于接口更改方面保留旧的接口
